### ISSUE TITLE
Error while trying to build

### ISSUE THREAD

**Issue by pythonlessons** [KorovkoAlexander/tensorrt_models#5]
So, today I tried to build.
OS win 10 with
- Python 3.7.2 64bit
- GPU - 1080TI
- TensorFlow 2.3.0
- Cuda - cuda_10.2.89_441.22_win10
- CudNN  - cudnn-10.2-windows10-x64-v7.6.5.32
- TensorRT-7.0.0.11

Tried to run `pip install .`, received following error:
```
C:\Users\HOME\Downloads\tensorrt_models>pip install .
Processing c:\users\home\downloads\tensorrt_models
Building wheels for collected packages: tensorrt-models
  Building wheel for tensorrt-models (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python37-64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\setup.py'"'"'; __file__='"'"'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\HOME\AppData\Local\Temp\pip-wheel-xgb8clh0'
       cwd: C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\
  Complete output (68 lines):
  running bdist_wheel
  running build
  running build_ext
  -- Building for: Visual Studio 16 2019
  -- Selecting Windows SDK version  to target Windows 10.0.17763.
  -- The C compiler identification is MSVC 19.27.29111.0
  -- The CXX compiler identification is MSVC 19.27.29111.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 (found version "10.2")
  CUDA found
  CMake Error at CMakeLists.txt:37 (add_subdirectory):
    The source directory

      C:/Users/HOME/AppData/Local/Temp/pip-req-build-9pdvyppy/pybind11

    does not contain a CMakeLists.txt file.


  CMake Error at CMakeLists.txt:38 (add_subdirectory):
    The source directory

      C:/Users/HOME/AppData/Local/Temp/pip-req-build-9pdvyppy/spdlog

    does not contain a CMakeLists.txt file.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/HOME/AppData/Local/Temp/pip-req-build-9pdvyppy/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\setup.py", line 68, in <module>
      zip_safe=False
    File "c:\python37-64\lib\site-packages\setuptools\__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "c:\python37-64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\python37-64\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\python37-64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python37-64\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "c:\python37-64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python37-64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\python37-64\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\python37-64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\python37-64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\setup.py", line 32, in run
      self.build_extension(ext)
    File "C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\setup.py", line 56, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "c:\python37-64\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=c:\\python37-64\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for tensorrt-models
  Running setup.py clean for tensorrt-models
Failed to build tensorrt-models
Installing collected packages: tensorrt-models
    Running setup.py install for tensorrt-models ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python37-64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\setup.py'"'"'; __file__='"'"'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HOME\AppData\Local\Temp\pip-record-y51g5q8z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python37-64\Include\tensorrt-models'
         cwd: C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\
    Complete output (70 lines):
    running install
    running build
    running build_ext
    -- Building for: Visual Studio 16 2019
    -- Selecting Windows SDK version  to target Windows 10.0.17763.
    -- The C compiler identification is MSVC 19.27.29111.0
    -- The CXX compiler identification is MSVC 19.27.29111.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 (found version "10.2")
    CUDA found
    CMake Error at CMakeLists.txt:37 (add_subdirectory):
      The source directory

        C:/Users/HOME/AppData/Local/Temp/pip-req-build-9pdvyppy/pybind11

      does not contain a CMakeLists.txt file.


    CMake Error at CMakeLists.txt:38 (add_subdirectory):
      The source directory

        C:/Users/HOME/AppData/Local/Temp/pip-req-build-9pdvyppy/spdlog

      does not contain a CMakeLists.txt file.


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/HOME/AppData/Local/Temp/pip-req-build-9pdvyppy/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\setup.py", line 68, in <module>
        zip_safe=False
      File "c:\python37-64\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "c:\python37-64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python37-64\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python37-64\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37-64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python37-64\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\python37-64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37-64\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37-64\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\python37-64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37-64\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\setup.py", line 32, in run
        self.build_extension(ext)
      File "C:\Users\HOME\AppData\Local\Temp\pip-req-build-9pdvyppy\setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "c:\python37-64\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=c:\\python37-64\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python37-64\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\setup.py'"'"'; __file__='"'"'C:\\Users\\HOME\\AppData\\Local\\Temp\\pip-req-build-9pdvyppy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HOME\AppData\Local\Temp\pip-record-y51g5q8z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python37-64\Include\tensorrt-models' Check the logs for full command output.

C:\Users\HOME\Downloads\tensorrt_models>
```
 have all files in downloads, installed cuda with cudnn.
in `CMakeLists.txt` made following changes:
```
include_directories(C:/Users/HOME/Downloads/TensorRT-7.0.0.11/include)

set(TensorRT_LIBRARIES C:/Users/HOME/Downloads/TensorRT-7.0.0.11/lib)
```
can you help running TensorRT on windows?
also tried to install .whl file:
```
C:\Users\HOME\Downloads>python -m pip install tensorrt_models-1.0.3-cp36-cp36m-win_amd64.whl
ERROR: tensorrt_models-1.0.3-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by KorovkoAlexander** [comment]
First, you should have cloned the repo with key --recursive. It will recursively clone pybind11 and spdlog libraries that are needed for building.
Second, please, try first to build the lib with TRT 7.1.3 (use the master branch of my lib).

**Comment by pythonlessons** [comment]
Thanks for reply, but on TRT download page there is no 7.1.3 for cuda 10.2:
https://developer.nvidia.com/nvidia-tensorrt-7x-download

**Comment by KorovkoAlexander** [comment]
Oh yes, i forgot that there is not TRT 7.1.3 for WIN. Use trt-7.0 branch instead.

**Comment by pythonlessons** [comment]
Would the results be the same if I would use Cuda 10.1 and trt-6.x?

**Comment by KorovkoAlexander** [comment]
A havent tested it in such setting and i wouldnt count that it will work well:( Have you solved your building problem with trt 7?

**Comment by pythonlessons** [comment]
Didn't tried it yet, for not it seems a little easier to run TRT on ubuntu, if  I will need it on Linux I'll come back! 
Thanks. Btw need better instructions
