### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by DreadOmen** [KorovkoAlexander/tensorrt_models#7]
My setup:

CUDA 10.2
Cudnn 8.0
Gtx 1060
Visual studio 2019 

First i cloned the github repo with your given command then i made ,,pip install .""
Then i made changes in the Cmakefile:
----------------------------
include_directories("E:/tensorrt/TensorRT-7.2.1.6/include/")

set(TensorRT_LIBRARIES "E:/tensorrt/TensorRT-7.2.1.6/lib/")
----------------------------

so when i type the pip install . command im getting those errors. 

Processing c:\users\caspa\tensorrt_models
Building wheels for collected packages: tensorrt-models
  Building wheel for tensorrt-models (setup.py) ... |  WARNING: Subprocess output does not appear to be encoded as cp1252
/  WARNING: Subprocess output does not appear to be encoded as cp1252
-  WARNING: Subprocess output does not appear to be encoded as cp1252
error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\caspa\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\caspa\\AppData\\Local\\Temp\\pip-req-build-eboupjqg\\setup.py'"'"'; __file__='"'"'C:\\Users\\caspa\\AppData\\Local\\Temp\\pip-req-build-eboupjqg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\caspa\AppData\Local\Temp\pip-wheel-7a714ps_'
       cwd: C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\
  Complete output (88 lines):
  running bdist_wheel
  running build
  running build_ext
  -- Building for: Visual Studio 16 2019
  -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
  -- The C compiler identification is MSVC 19.27.29111.0
  -- The CXX compiler identification is MSVC 19.27.29111.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: E:/Visual Studio 2019/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: E:/Visual Studio 2019/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 (found version "10.2")
  CUDA found
  -- Found PythonInterp: C:/Users/caspa/anaconda3/envs/tensorflow/python.exe (found version "3.8.6")
  -- Found PythonLibs: C:/Users/caspa/anaconda3/envs/tensorflow/libs/Python38.lib
  -- pybind11 v2.3.dev1
  -- Build spdlog: 1.4.3
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
  -- Found Threads: TRUE
  -- Build type: Release
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/caspa/AppData/Local/Temp/pip-req-build-eboupjqg/build/temp.win-amd64-3.8/Release
  Microsoft (R)-Build-Engine, Version 16.7.0+b89cb5fde f\x81r .NET Framework
  Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  E:\Visual Studio 2019\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: Das Zwischenverzeichnis oder das Ausgabeverzeichnis darf nicht im tempor„ren Verzeichnis enthalten sein, da dies zu Problemen mit dem inkrementellen Build f\x81hren kann. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\ZERO_CHECK.vcxproj]
    Checking Build System
  E:\Visual Studio 2019\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: Das Zwischenverzeichnis oder das Ausgabeverzeichnis darf nicht im tempor„ren Verzeichnis enthalten sein, da dies zu Problemen mit dem inkrementellen Build f\x81hren kann. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    Building Custom Rule C:/Users/caspa/AppData/Local/Temp/pip-req-build-eboupjqg/spdlog/CMakeLists.txt
  cl : befehlszeile warning D9002: Unbekannte Option "-O3" wird ignoriert. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    spdlog.cpp
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger-inl.h(184,13): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger-inl.h(184,13): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    stdout_sinks.cpp
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(160): message : Siehe Verweis auf die gerade kompilierte Instanziierung "void spdlog::logger::log<>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t)" der Funktions-Vorlage. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    color_sinks.cpp
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(160): message : Siehe Verweis auf die gerade kompilierte Instanziierung "void spdlog::logger::log<>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t)" der Funktions-Vorlage. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    file_sinks.cpp
    async.cpp
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/async_logger-inl.h(62,13): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/async_logger-inl.h(62,13): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    fmt.cpp
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/fmt/bundled/format-inl.h(898,11): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
  C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/fmt/bundled/format-inl.h(898,11): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    Code wird generiert...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\setup.py", line 59, in <module>
      setup(
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\setup.py", line 32, in run
      self.build_extension(ext)
    File "C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\setup.py", line 57, in build_extension
      subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
    File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for tensorrt-models
  Running setup.py clean for tensorrt-models
Failed to build tensorrt-models
Installing collected packages: tensorrt-models
    Running setup.py install for tensorrt-models ... |    WARNING: Subprocess output does not appear to be encoded as cp1252
/    WARNING: Subprocess output does not appear to be encoded as cp1252
-    WARNING: Subprocess output does not appear to be encoded as cp1252
error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\caspa\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\caspa\\AppData\\Local\\Temp\\pip-req-build-eboupjqg\\setup.py'"'"'; __file__='"'"'C:\\Users\\caspa\\AppData\\Local\\Temp\\pip-req-build-eboupjqg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\caspa\AppData\Local\Temp\pip-record-l7of4ric\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\caspa\anaconda3\envs\tensorflow\Include\tensorrt-models'
         cwd: C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\
    Complete output (90 lines):
    running install
    running build
    running build_ext
    -- Building for: Visual Studio 16 2019
    -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
    -- The C compiler identification is MSVC 19.27.29111.0
    -- The CXX compiler identification is MSVC 19.27.29111.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: E:/Visual Studio 2019/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: E:/Visual Studio 2019/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2 (found version "10.2")
    CUDA found
    -- Found PythonInterp: C:/Users/caspa/anaconda3/envs/tensorflow/python.exe (found version "3.8.6")
    -- Found PythonLibs: C:/Users/caspa/anaconda3/envs/tensorflow/libs/Python38.lib
    -- pybind11 v2.3.dev1
    -- Build spdlog: 1.4.3
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    -- Build type: Release
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/caspa/AppData/Local/Temp/pip-req-build-eboupjqg/build/temp.win-amd64-3.8/Release
    Microsoft (R)-Build-Engine, Version 16.7.0+b89cb5fde f\x81r .NET Framework
    Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

    E:\Visual Studio 2019\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: Das Zwischenverzeichnis oder das Ausgabeverzeichnis darf nicht im tempor„ren Verzeichnis enthalten sein, da dies zu Problemen mit dem inkrementellen Build f\x81hren kann. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\ZERO_CHECK.vcxproj]
      Checking Build System
    E:\Visual Studio 2019\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: Das Zwischenverzeichnis oder das Ausgabeverzeichnis darf nicht im tempor„ren Verzeichnis enthalten sein, da dies zu Problemen mit dem inkrementellen Build f\x81hren kann. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
      Building Custom Rule C:/Users/caspa/AppData/Local/Temp/pip-req-build-eboupjqg/spdlog/CMakeLists.txt
    cl : befehlszeile warning D9002: Unbekannte Option "-O3" wird ignoriert. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
      spdlog.cpp
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger-inl.h(184,13): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger-inl.h(184,13): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
      stdout_sinks.cpp
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(160): message : Siehe Verweis auf die gerade kompilierte Instanziierung "void spdlog::logger::log<>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t)" der Funktions-Vorlage. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
      color_sinks.cpp
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(160): message : Siehe Verweis auf die gerade kompilierte Instanziierung "void spdlog::logger::log<>(spdlog::source_loc,spdlog::level::level_enum,spdlog::string_view_t)" der Funktions-Vorlage. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/logger.h(86,1): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
      file_sinks.cpp
      async.cpp
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/async_logger-inl.h(62,13): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/async_logger-inl.h(62,13): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
      fmt.cpp
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/fmt/bundled/format-inl.h(898,11): error C2220: Die folgende Warnung wird als Fehler behandelt. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
    C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\spdlog\include\spdlog/fmt/bundled/format-inl.h(898,11): warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]
      Code wird generiert...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\setup.py", line 59, in <module>
        setup(
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\setup.py", line 32, in run
        self.build_extension(ext)
      File "C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\setup.py", line 57, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "C:\Users\caspa\anaconda3\envs\tensorflow\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\caspa\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\caspa\\AppData\\Local\\Temp\\pip-req-build-eboupjqg\\setup.py'"'"'; __file__='"'"'C:\\Users\\caspa\\AppData\\Local\\Temp\\pip-req-build-eboupjqg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\caspa\AppData\Local\Temp\pip-record-l7of4ric\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\caspa\anaconda3\envs\tensorflow\Include\tensorrt-models' Check the logs for full command output.

**Comment by zilingzhang** [comment]
As the warning suggests,

warning C4530: C++-Handler verwendet, aber Entladesemantik ist nicht aktiviert. Geben Sie /EHsc an. [C:\Users\caspa\AppData\Local\Temp\pip-req-build-eboupjqg\build\temp.win-amd64-3.8\Release\spdlog\spdlog.vcxproj]

Please add 

set(CMAKE_CXX_FLAGS "/O2 /EHsc") to the CMakeLists.txt in the spdlog library
